import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
const kumbh = Kumbh_Sans({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Role based app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${kumbh.className}`}>{children}</body>
      </html>
    </SessionProvider>
  );
}
